-- ==========================================
-- AIOX EMAIL CAMPAIGN SCHEMA
-- ==========================================

-- 1. Templates de E-mail
CREATE TABLE IF NOT EXISTS public.email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    name TEXT NOT NULL,
    description TEXT,
    content_json JSONB NOT NULL, -- Estrutura do editor visual
    content_html TEXT NOT NULL, -- HTML final renderizado
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Segmentos B2B
CREATE TABLE IF NOT EXISTS public.segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    name TEXT NOT NULL,
    filters JSONB NOT NULL, -- Ex: { \"status\": \"Lead\", \"min_value\": 50000 }
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Campanhas
CREATE TABLE IF NOT EXISTS public.campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    template_id BIGINT REFERENCES public.email_templates(id),
    segment_id BIGINT REFERENCES public.segments(id),
    title TEXT NOT NULL,
    subject TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'sending', 'sent', 'failed')),
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Logs de Envio
CREATE TABLE IF NOT EXISTS public.email_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT REFERENCES public.campaigns(id),
    lead_id BIGINT REFERENCES public.leads(id),
    status TEXT NOT NULL,
    error_message TEXT,
    sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS em tudo (Zero Trust)
ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;

-- Políticas: Somente o dono acessa seus dados
CREATE POLICY \"Users manage their own templates\" ON public.email_templates FOR ALL USING (auth.uid() = user_id);
CREATE POLICY \"Users manage their own segments\" ON public.segments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY \"Users manage their own campaigns\" ON public.campaigns FOR ALL USING (auth.uid() = user_id);
CREATE POLICY \"Users view their own email logs\" ON public.email_logs FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.campaigns WHERE campaigns.id = email_logs.campaign_id AND campaigns.user_id = auth.uid())
);

COMMENT ON TABLE public.campaigns IS 'Gestão de campanhas de e-mail B2B.';
