-- ==========================================
-- AIOX ANTI-HACKER SCHEMA: AUDIT LOGS
-- ==========================================

-- 1. Criar tabela de Auditoria
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    record_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    old_data JSONB,
    new_data JSONB,
    user_id UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Habilitar RLS nos Logs (Ninguém vê, só admin/service_role)
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Audit logs are restricted" ON public.audit_logs FOR SELECT USING (false);

-- 3. Função de Trigger para capturar mudanças
CREATE OR REPLACE FUNCTION public.process_leads_audit()
RETURNS TRIGGER AS \$\$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO public.audit_logs (table_name, record_id, action, new_data)
        VALUES (TG_TABLE_NAME, NEW.id, 'INSERT', to_jsonb(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public.audit_logs (table_name, record_id, action, old_data, new_data)
        VALUES (TG_TABLE_NAME, NEW.id, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO public.audit_logs (table_name, record_id, action, old_data)
        VALUES (TG_TABLE_NAME, OLD.id, 'DELETE', to_jsonb(OLD));
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
\$\$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Aplicar o Trigger na tabela de Leads
DROP TRIGGER IF EXISTS leads_audit_trigger ON public.leads;
CREATE TRIGGER leads_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.leads
FOR EACH ROW EXECUTE FUNCTION public.process_leads_audit();

COMMENT ON TABLE public.audit_logs IS 'Registro imutável de alterações para auditoria de segurança.';
