-- ==========================================
-- AIOX ANTI-HACKER SCHEMA: LEADS
-- ==========================================

-- 1. Criar a tabela de Leads
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    company TEXT NOT NULL,
    contact TEXT NOT NULL,
    segment TEXT NOT NULL,
    value NUMERIC(15, 2) NOT NULL DEFAULT 0,
    owner TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Lead', 'Contato', 'Proposta', 'Fechado')),
    last_touch DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Habilitar Row Level Security (CRÍTICO)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- 3. Criar Políticas de Acesso (Zero Trust)
-- Somente o dono do dado pode VER seus leads
DO \$\$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view their own leads') THEN
        CREATE POLICY "Users can view their own leads" ON public.leads FOR SELECT USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can insert their own leads') THEN
        CREATE POLICY "Users can insert their own leads" ON public.leads FOR INSERT WITH CHECK (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update their own leads') THEN
        CREATE POLICY "Users can update their own leads" ON public.leads FOR UPDATE USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can delete their own leads') THEN
        CREATE POLICY "Users can delete their own leads" ON public.leads FOR DELETE USING (auth.uid() = user_id);
    END IF;
END \$\$;

-- 4. Comentários de Auditoria
COMMENT ON TABLE public.leads IS 'Armazenamento de Leads com proteção RLS por usuário.';
